package com.study.model;

import java.util.Date;

public class User
{
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.id
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	private Long id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.name
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.age
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	private Integer age;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.email
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	private String email;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.createTime
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.loginTime
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	private Date loginTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.teacherId
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	private Long teacherId;

	/**
	 * 实现1对1的查询支持
	 */
	private Teacher teacher;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.gender
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	private String gender;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.id
	 *
	 * @return the value of user.id
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	public Long getId()
	{
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.id
	 *
	 * @param id
	 *            the value for user.id
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	public void setId(Long id)
	{
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.name
	 *
	 * @return the value of user.name
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.name
	 *
	 * @param name
	 *            the value for user.name
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	public void setName(String name)
	{
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.age
	 *
	 * @return the value of user.age
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	public Integer getAge()
	{
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.age
	 *
	 * @param age
	 *            the value for user.age
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	public void setAge(Integer age)
	{
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.email
	 *
	 * @return the value of user.email
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	public String getEmail()
	{
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.email
	 *
	 * @param email
	 *            the value for user.email
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	public void setEmail(String email)
	{
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.createTime
	 *
	 * @return the value of user.createTime
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	public Date getCreateTime()
	{
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.createTime
	 *
	 * @param createTime
	 *            the value for user.createTime
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	public void setCreateTime(Date createTime)
	{
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.loginTime
	 *
	 * @return the value of user.loginTime
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	public Date getLoginTime()
	{
		return loginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.loginTime
	 *
	 * @param loginTime
	 *            the value for user.loginTime
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	public void setLoginTime(Date loginTime)
	{
		this.loginTime = loginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.teacherId
	 *
	 * @return the value of user.teacherId
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	public Long getTeacherId()
	{
		return teacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.teacherId
	 *
	 * @param teacherId
	 *            the value for user.teacherId
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	public void setTeacherId(Long teacherId)
	{
		this.teacherId = teacherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.gender
	 *
	 * @return the value of user.gender
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	public String getGender()
	{
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.gender
	 *
	 * @param gender
	 *            the value for user.gender
	 *
	 * @mbg.generated Tue May 30 22:26:58 CST 2017
	 */
	public void setGender(String gender)
	{
		this.gender = gender == null ? null : gender.trim();
	}

	public Teacher getTeacher()
	{
		return teacher;
	}

	public void setTeacher(Teacher teacher)
	{
		this.teacher = teacher;
	}
}